export const productData = [
	{
		id: 1,
		name: 'Brown Brim',
		imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
		price: 25,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Calgary',
		sellerId: '1234',
		category: 'Deals',
	},
	{
		id: 2,
		name: 'Blue Beanie',
		imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
		price: 18,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Calgary',
		sellerId: '1234',
		category: 'Deals',
	},
	{
		id: 3,
		name: 'Brown Cowboy',
		imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
		price: 35,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Calgary',
		sellerId: '1234111',
		category: 'Deals',
	},
	{
		id: 4,
		name: 'Grey Brim',
		imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
		price: 25,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Calgary',
		sellerId: '123411',
		category: 'Deals',
	},
	{
		id: 5,
		name: 'Green Beanie',
		imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
		price: 18,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Calgary',
		sellerId: '12341',
		category: 'Deals',
	},
	{
		id: 6,
		name: 'Palm Tree Cap',
		imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
		price: 14,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Calgary',
		sellerId: '12341',
		category: 'Deals',
	},
	{
		id: 7,
		name: 'Red Beanie',
		imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
		price: 18,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Calgary',
		sellerId: '12341',
		category: 'Deals',
	},
	{
		id: 8,
		name: 'Wolf Cap',
		imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
		price: 14,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Camrose',
		sellerId: '12341111',
		category: 'Deals',
	},
	{
		id: 9,
		name: 'Blue Snapback',
		imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
		price: 16,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Camrose',
		sellerId: '1232290924',
		category: 'Deals',
	},
	{
		id: 10,
		name: 'Adidas NMD',
		imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
		price: 220,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Camrose',
		sellerId: '12223422222',
		category: 'Cars & Vehicles',
	},
	{
		id: 11,
		name: 'Adidas Yeezy',
		imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
		price: 280,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Chestermere',
		sellerId: '123222224',
		category: 'Cars & Vehicles',
	},
	{
		id: 12,
		name: 'Black Converse',
		imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
		price: 110,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Chestermere',
		sellerId: '1234',
		category: 'Cars & Vehicles',
	},
	{
		id: 13,
		name: 'Nike White AirForce',
		imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
		price: 160,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Chestermere',
		sellerId: '1234',
		category: 'Cars & Vehicles',
	},
	{
		id: 14,
		name: 'Nike Red High Tops',
		imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
		price: 160,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Chestermere',
		sellerId: '123334',
		category: 'Cars & Vehicles',
	},
	{
		id: 15,
		name: 'Nike Brown High Tops',
		imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
		price: 160,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Edmonton',
		sellerId: '1444234',
		category: 'Cars & Vehicles',
	},
	{
		id: 16,
		name: 'Air Jordan Limited',
		imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
		price: 190,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Edmonton',
		sellerId: '12434',
		category: 'Cars & Vehicles',
	},
	{
		id: 17,
		name: 'Timberlands',
		imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
		price: 200,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Edmonton',
		sellerId: '1444234',
		category: 'Cars & Vehicles',
	},

	{
		id: 18,
		name: 'Black Jean Shearling',
		imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
		price: 125,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Fort McMurray',
		sellerId: '123455',
		category: 'Furniture',
	},
	{
		id: 19,
		name: 'Blue Jean Jacket',
		imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
		price: 90,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Fort Saskatchewan',
		sellerId: '123456666',
		category: 'Furniture',
	},
	{
		id: 20,
		name: 'Grey Jean Jacket',
		imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
		price: 90,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Fort Saskatchewan',
		sellerId: '12346',
		category: 'Furniture',
	},
	{
		id: 21,
		name: 'Brown Shearling',
		imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
		price: 165,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Grand Prairie',
		sellerId: '1236664',
		category: 'Furniture',
	},
	{
		id: 22,
		name: 'Tan Trench',
		imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
		price: 185,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Grande Prairie',
		sellerId: '12374',
		category: 'Furniture',
	},

	{
		id: 23,
		name: 'Blue Tanktop',
		imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
		price: 25,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Leduc',
		sellerId: '123774',
		category: 'Electronics',
	},
	{
		id: 24,
		name: 'Floral Blouse',
		imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
		price: 20,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Lethbridge',
		sellerId: '1237774',
		category: 'Electronics',
	},
	{
		id: 25,
		name: 'Floral Dress',
		imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
		price: 80,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Lethbridge',
		sellerId: '123777774',
		category: 'Electronics',
	},
	{
		id: 26,
		name: 'Red Dots Dress',
		imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
		price: 80,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Lloydminster',
		sellerId: '12388884',
		category: 'Electronics',
	},
	{
		id: 27,
		name: 'Striped Sweater',
		imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
		price: 45,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Leduc',
		sellerId: '12384',
		category: 'Electronics',
	},
	{
		id: 28,
		name: 'Yellow Track Suit',
		imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
		price: 135,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Red Deer',
		sellerId: '1999234',
		category: 'Electronics',
	},
	{
		id: 29,
		name: 'White Blouse',
		imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
		price: 20,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Red Deer',
		sellerId: '1234',
		category: 'Electronics',
	},
	{
		id: 30,
		name: 'Camo Down Vest',
		imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
		price: 325,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Medicine Hat',
		sellerId: '19234',
		category: 'Real Estate',
	},
	{
		id: 31,
		name: 'Floral T-shirt',
		imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
		price: 20,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'St Alberta',
		sellerId: '129934',
		category: 'Real Estate',
	},
	{
		id: 32,
		name: 'Black & White Longsleeve',
		imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
		price: 25,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'St Albert',
		sellerId: '199999234',
		category: 'Real Estate',
	},
	{
		id: 33,
		name: 'Pink T-shirt',
		imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
		price: 25,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Brooks',
		sellerId: '120000034',
		category: 'Real Estate',
	},
	{
		id: 34,
		name: 'Jean Long Sleeve',
		imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
		price: 40,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: 'Brooks',
		sellerId: '000000123',
		category: 'Real Estate',
	},
	{
		id: 35,
		name: 'Burgundy T-shirt',
		imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		price: 25,
		imageUrls: [
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
			'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
		],
		description: 'Something to describe the product. ',
		condition: "It's a useless piece of junk.",
		address: 'Nowhere St. NW',
		city: '  Brooks',
		sellerId: '112313123132234',
		category: 'Real Estate',
	},
];
